<?php
/**
 * Copyright © 2017 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Ginger\Payments\Block\Info\Banktransfer
 */
?>
<dl class="payment-method banktransfer">
    <dt class="title"><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <?php if ($block->getMailingAddress()) { ?>
        <dd class="content">
            <address class="banktransfer mailing address">
                <?php /* @noEscape */
                echo nl2br($block->escapeHtml($block->getMailingAddress())) ?>
            </address>
        </dd>
    <?php } ?>
</dl>