<?php
/**
 * Copyright © 2017 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block Ginger\Payments\Block\Adminhtml\Render\Header
 */
?>
<div class="mm-block-ginger">
    <a class="helpbutton" href="https://merchant-portal.gingerpayments.com/login.php" target="_blank"></a>
    <p>
        <strong>Developed by Magmodules.</strong>
        A Magento only eCommerce Agency located in the Netherlands.
    </p>
    <table>
        <tbody>
            <tr>
                <td>
                    <div class="icon1"></div>
                    <a href="https://www.magmodules.eu/" target="_blank">Visit Magmodules.eu</a>
                </td>
                <td>
                    <div class="icon2"></div>
                    <a href="https://www.gingerpayments.com/contact" target="_blank">Support</a>
                </td>
                <td>
                    <div class="icon3"></div>
                    <a href="https://merchant-portal.gingerpayments.com/login.php" target="_blank">Merchant Portal</a>
                </td>
            </tr>
        </tbody>
    </table>
</div>