<?php
/**
 * Copyright © 2017 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block Ginger\Payments\Block\Info\Banktransfer
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($block->getInfo()->getAdditionalInformation()) { ?>
    <?php if ($block->getMailingAddress()) { ?>
        <div class="ing-mailing-address">
            <?php /* @noEscape */ echo nl2br($block->escapeHtml($block->getMailingAddress())) ?>
        </div>
    <?php } ?>
<?php } ?>
